-- Combined SQL dump: roles + positions + users
-- Import order: roles -> positions -> users
-- Intended for a NEW MariaDB/MySQL database where these tables do not yet exist.
-- Source files generated by phpMyAdmin on Aug 10, 2026.

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

START TRANSACTION;

-- ============================================================
-- TABLE: roles
-- ============================================================

CREATE TABLE `roles` (
  `role_id` int(11) NOT NULL,
  `role` varchar(255) DEFAULT NULL,
  `create_at` datetime DEFAULT current_timestamp(),
  `update_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `delete_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `roles`
--

INSERT INTO `roles` (`role_id`, `role`, `create_at`, `update_at`, `delete_at`) VALUES
(1, 'teacher', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(2, 'staff', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(3, 'admin', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(4, 'dept_head', '2025-09-21 19:03:02', '2025-09-21 19:03:05', NULL),
(5, 'executive', '2026-02-12 16:57:37', NULL, NULL),
(6, 'academic_designer', '2026-07-06 16:05:21', NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `roles`
--
ALTER TABLE `roles`
  ADD PRIMARY KEY (`role_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `roles`
--
ALTER TABLE `roles`
  MODIFY `role_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

-- ============================================================
-- TABLE: positions
-- ============================================================

CREATE TABLE `positions` (
  `position_id` int(11) NOT NULL,
  `position_name` varchar(255) DEFAULT NULL,
  `is_active` enum('yes','no') DEFAULT 'yes',
  `create_at` datetime DEFAULT current_timestamp(),
  `update_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  `delete_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `positions`
--

INSERT INTO `positions` (`position_id`, `position_name`, `is_active`, `create_at`, `update_at`, `delete_at`) VALUES
(1, 'อาจารย์', 'yes', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(2, 'รองศาสตราจารย์', 'yes', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(3, 'พนักงานธุรการ', 'yes', '2025-06-24 16:49:13', '2025-06-24 16:49:13', NULL),
(4, 'เจ้าหน้าที่บริหารงานทั่วไป', 'yes', NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `positions`
--
ALTER TABLE `positions`
  ADD PRIMARY KEY (`position_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `positions`
--
ALTER TABLE `positions`
  MODIFY `position_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

-- ============================================================
-- TABLE: users
-- ============================================================

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `user_fname` varchar(255) DEFAULT NULL,
  `user_lname` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `email_notification` varchar(255) DEFAULT NULL,
  `scholar_author_id` varchar(64) DEFAULT NULL,
  `scopus_id` varchar(100) DEFAULT NULL,
  `thaijo_author_id` varchar(100) DEFAULT NULL,
  `thaijo_sync_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `password` varchar(255) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `position_id` int(11) DEFAULT NULL,
  `date_of_employment` date DEFAULT NULL,
  `create_at` datetime DEFAULT current_timestamp(),
  `update_at` datetime DEFAULT NULL,
  `delete_at` datetime DEFAULT NULL,
  `prefix` varchar(50) DEFAULT NULL,
  `manage_position` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `position_en` varchar(255) DEFAULT NULL,
  `prefix_position_en` varchar(50) DEFAULT NULL,
  `Name_en` varchar(255) DEFAULT NULL,
  `suffix_en` varchar(50) DEFAULT NULL,
  `TEL` varchar(50) DEFAULT NULL,
  `TELformat` varchar(50) DEFAULT NULL,
  `TEL_ENG` varchar(50) DEFAULT NULL,
  `manage_position_en` varchar(255) DEFAULT NULL,
  `LAB_Name` varchar(255) DEFAULT NULL,
  `Room` varchar(255) DEFAULT NULL,
  `CP_WEB_ID` varchar(255) DEFAULT NULL,
  `Is_active` char(1) DEFAULT 'A',
  `last_login_at` datetime DEFAULT NULL,
  `course_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `user_fname`, `user_lname`, `gender`, `email`, `email_notification`, `scholar_author_id`, `scopus_id`, `thaijo_author_id`, `thaijo_sync_enabled`, `password`, `role_id`, `position_id`, `date_of_employment`, `create_at`, `update_at`, `delete_at`, `prefix`, `manage_position`, `position`, `position_en`, `prefix_position_en`, `Name_en`, `suffix_en`, `TEL`, `TELformat`, `TEL_ENG`, `manage_position_en`, `LAB_Name`, `Room`, `CP_WEB_ID`, `Is_active`, `last_login_at`, `course_id`) VALUES
(1001, 'งามนิจ', 'อาจอินทร์', 'female', 'ngamnij@kku.ac.th', 'ngamnij@kku.ac.th', 'GsfOlmYAAAAJ', '6506313280', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-07-15 13:52:37', NULL, 'รศ. ดร.', '', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'ngamnij arch-int', 'Ph.D.', '089-6222316', '08 9622 2316', '+668 9622 2316', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', '', 'https://computing.kku.ac.th/ngamnij.arch-int', 'A', '2026-07-15 13:52:37', NULL),
(1002, 'พุธษดี', 'ศิริแสงตระกูล', 'female', 'pusadee@kku.ac.th', 'pusadee@kku.ac.th', 'E01V5gUAAAAJ', '6506519783', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-07-10 11:00:11', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'pusadee seresangtakul', 'Ph.D.', '080-4140401', '08 0414 0401', '+668 0414 0401', '', 'Natural Language and Speech Processing Lab (NLSP)', '', 'https://computing.kku.ac.th/pusadee.seresangtakul', 'A', '2026-07-10 11:00:11', NULL),
(1003, 'อุรฉัตร ', 'โคแก้ว', 'female', 'urachart@kku.ac.th', 'urachart@kku.ac.th', '1RIrvgkAAAAJ', '55453256400', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'รศ. ดร.', '', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'urachart kokaew', 'Ph.D.', '086-6329529', '08 6632 9529', '+668 6632 9529', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', 'SC9333', 'https://computing.kku.ac.th/urachart.kokaew', 'A', NULL, NULL),
(1004, 'ปัญญาพล', 'หอระตะ', 'male', 'punhor1@kku.ac.th', 'punhor1@kku.ac.th', '00JXDiUAAAAJ', '54895164800', NULL, 0, '$2a$10$b1NahOOZeHntpE3I9gnod.XPD/Tgi4KznaQ4EIoES4sWwBbTPgZUi', 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'รศ. ดร.', '', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'punyaphol horata', 'Ph.D.', '095-1689845', '09 5168 9845', '+669 5168 9845', '', 'Advanced Smart Computing Lab', '', 'https://computing.kku.ac.th/punyaphol.horata', 'A', NULL, NULL),
(1005, 'วชิราวุธ', 'ธรรมวิเศษ', 'male', 'twachi@kku.ac.th', 'twachi@kku.ac.th', 'zmQuQoIAAAAJ', '55367960800', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Wachirawut Thamviset', 'Ph.D.', '081-3805203', '08 1380 5203', '+668 1380 5203', '', 'Machine Learning and Intelligent Systems (MLIS) Lab', '', 'https://computing.kku.ac.th/wachirawut.tamviset', 'A', NULL, NULL),
(1006, 'สุมณฑา', 'เกษมวิลาศ', 'female', 'sumkas@kku.ac.th', 'sumkas@kku.ac.th', 'jchtQ6gAAAAJ', '26424681900', NULL, 0, '$2a$10$GFC1Yqlw4tn0Kl.IbvsARO6daRXPDjihS3p3KHot2meCmCnN2D1Y.', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-04-17 17:02:32', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Sumonta Kasemvilas', 'Ph.D.', '094-2519245', '09 4251 9245', '+669 4251 9245', '', 'Hardware-Human Interface and Communications (H2I-Comm) Lab', 'SC9363', 'https://computing.kku.ac.th/sumonta.kasemvilas', 'A', '2026-04-17 17:02:32', NULL),
(1007, 'สิรภัทร', 'เชี่ยวชาญวัฒนา', 'female', 'sunkra@kku.ac.th', 'sunkra@kku.ac.th', NULL, '6506082174', NULL, 0, '$2a$10$4aHr0IzNRrxDZbqOdM6NOOeRIMnYKHBdEly8zyP4jQGrWfZzQPXgG', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-07-22 13:58:37', NULL, 'รศ. ดร.', 'คณบดี', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'sirapat chiewchanwattana', 'Ph.D.', '086-8509784', '08 6850 9784', '+668 6850 9784', '', 'Advanced Smart Computing (ASC) Lab', '', 'https://computing.kku.ac.th/sirapat.chiewchanwattana', 'A', '2026-07-22 13:53:37', NULL),
(1008, 'บุญทรัพย์', 'ไวคำ', 'male', 'boonsup@kku.ac.th', 'boonsup@kku.ac.th', 'sAp1BWsAAAAJ', '55453094300', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'boonsup waikham', '', '080-7668868', '08 0766 8868', '+668 0766 8868', '', '', '', 'https://computing.kku.ac.th/boonsup.waikham', 'A', NULL, NULL),
(1009, 'อุราวรรณ', 'จันทร์เกษ', 'female', 'curawa@kku.ac.th', 'curawa@kku.ac.th', NULL, '55349311900', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'urawan chanket', 'Ph.D.', '087-6780595', '08 7678 0595', '+668 7678 0595', '', 'Geo-informatics, NEGISTDA', '', 'https://computing.kku.ac.th/urawan.chanket', 'A', NULL, NULL),
(1010, 'วรารัตน์', 'สงฆ์แป้น', 'female', 'wararat@kku.ac.th ', 'wararat@kku.ac.th ', 'VfmVWLIAAAAJ', '56688578200', NULL, 0, '$2a$10$X/RYEMTk0M8MsIq0CUI5leOmGrwk7B6lVsc.tiji46GI7Bocg00q6', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-08-07 13:02:30', NULL, 'รศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'wararat songpan', 'Ph.D.', '080-4111279', '08 0411 1279', '+668 0411 1279', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', '', 'https://computing.kku.ac.th/wararat.songpan', 'A', '2026-08-07 13:02:30', NULL),
(1011, 'ชัยพล', 'กีรติกสิกร', 'male', 'chaiyapon@kku.ac.th', 'chaiyapon@kku.ac.th', NULL, '54885245300', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'รศ. ดร.', '', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'chaiyapon keeratikasikorn', 'Ph.D.', '084-6499463', '08 4649 9463', '+668 4649 9463', '', '', '', 'https://computing.kku.ac.th/chaiyapon.keeratikasikorn', 'A', NULL, NULL),
(1012, 'ปวีณา', 'วันชัย', 'female', 'wpaweena@kku.ac.th', 'wpaweena@kku.ac.th', NULL, '57194219816', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'paweena wanchai', 'Ph.D.', '087-6926662', '08 7692 6662', '+668 7692 6662', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', 'SC9332', 'https://computing.kku.ac.th/paweena.wanchai', 'A', NULL, NULL),
(1013, 'สิลดา', 'อินทรโสธรฉันท์', 'female', 'silain@kku.ac.th', 'silain@kku.ac.th', NULL, '26422303100', NULL, 0, '$2a$10$F9GiEayfkDSvfnKbw6Vx2eg5wXUW6hoTPMspciixArllsjzfGkf/i', 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'silada intarasothonchun', 'Ph.D.', '094-2842356', '09 4284 2356', '+669 4284 2356', '', '', '', 'https://computing.kku.ac.th/silada.intarasothonchun', 'A', NULL, NULL),
(1014, 'ณกร', 'วัฒนกิจ', 'male', 'nagon@kku.ac.th', 'nagon@kku.ac.th', NULL, '55349545600', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-08-10 13:50:46', NULL, 'ผศ. ดร.', 'รองคณบดีฝ่ายวิชาการ', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'nagon watanakij', 'Ph.D.', '085-0040090', '08 5004 0090', '+668 5004 0090', '', '', '', 'https://computing.kku.ac.th/nagon.watanakij', 'A', '2026-08-10 13:50:46', NULL),
(1015, 'มัลลิกา', 'วัฒนะ', 'female', 'monlwa@kku.ac.th', 'monlwa@kku.ac.th', '6aUFvc8AAAAJ', '35147082800', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Monlica Wattana', 'Ph.D.', '086-8680988', '08 6868 0988', '+668 6868 0988', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', 'SC9329', 'https://computing.kku.ac.th/monlica.wattana', 'A', NULL, NULL),
(1016, 'สายยัญ', 'สายยศ', 'male', 'saiyan@kku.ac.th', 'saiyan@kku.ac.th', 'ksJyxM4AAAAJ', '36669331500', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-04-18 09:37:11', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'saiyan saiyod', 'Ph.D.', '089-6204227', '08 9620 4227', '+668 9620 4227', '', '', '', 'https://computing.kku.ac.th/saiyan.saiyod', 'A', '2026-04-18 09:37:11', NULL),
(1017, 'พิพัธน์', 'เรืองแสง', 'male', 'reungsang@kku.ac.th ', 'reungsang@kku.ac.th ', 'E1k8_KEAAAAJ', '7801595668', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Pipat Reungsang', 'Ph.D.', '097-3217810', '09 7321 7810', '+669 7321 7810', '', '', '', 'https://computing.kku.ac.th/pipat.reungsang', 'A', NULL, NULL),
(1018, 'จักรชัย', 'โสอินทร์', 'male', 'chakso@kku.ac.th', 'chakso@kku.ac.th', NULL, '57218454758', NULL, 0, '$2a$10$C.srkcvnv1OVk/C/ZQa8XeEyQRmeL5fzIn9GcmDmC.gJ.EBHGIhlO', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-06-26 21:09:49', NULL, 'ศ. ดร.', '', 'ศาสตราจารย์', 'Professor', 'Prof.', 'Chakchai So-In', 'Ph.D.', '094-5149644', '09 4514 9644', '+669 4514 9644', '', 'IEEE/ACM Senior Members', '', 'https://computing.kku.ac.th/chakchai.so-in', 'A', '2026-06-26 21:09:49', NULL),
(1019, 'คำรณ', 'สุนัติ', 'male', 'skhamron@kku.ac.th', 'skhamron@kku.ac.th', 'eMdpRLEAAAAJ', '56028467300', NULL, 0, '$2a$10$/.enWAhaWadwA9uF07.iseEEPwv6edV7ZiXrjBKCQcKSoaAD.iBIy', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-01-05 10:58:17', NULL, 'รศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'khamron sunat', 'Ph.D.', '080-4613391', '08 0461 3391', '+668 0461 3391', '', 'Advanced Smart Computing (ASC) Lab', '', 'https://computing.kku.ac.th/khamron.sunat', 'A', NULL, NULL),
(1020, 'ชิตสุธา', 'สุ่มเล็ก', 'female', 'chitsutha@kku.ac.th', 'chitsutha@kku.ac.th', 'ghQ1lTAAAAAJ', '36024421200', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'chitsutha soomlek', 'Ph.D.', '091-8654422', '091-8654422', '-', '', '\r Department of Computer Science ', ' SC9327', 'https://computing.kku.ac.th/chitsutha.soomlek', 'A', NULL, NULL),
(1021, 'ศรัณย์', 'อภิชนตระกูล', 'male', 'sarunap@kku.ac.th', 'sarunap@kku.ac.th', 'yqNNqdAAAAAJ', '57739852500', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', 'รองคณบดีฝ่ายบริหาร', 'อาจารย์', 'Lecturer', '', 'Sarun Apichontrakul', 'Ph.D.', '084-1056767', '08 4105 6767', '+668 4105 6767', '', '', '', 'https://computing.kku.ac.th/sarun.apichontrakul', 'A', NULL, NULL),
(1022, 'ธนพล', 'ตั้งชูพงศ์', 'male', 'thanaphon@kku.ac.th', 'thanaphon@kku.ac.th', 'xF4E8-gAAAAJ', '35410771100', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ.', '', 'อาจารย์', 'Lecturer', '', 'Thanaphon Tangchoopong', '', '065-5219359', '06 5521 9359', '+666 5521 9359', '', 'Advanced Smart Computing (ASC) Lab', 'SC9328', 'https://computing.kku.ac.th/thanaphon.tangchoopong', 'A', NULL, NULL),
(1023, 'วรัญญา', 'วรรณศรี', 'female', 'waruwu@kku.ac.th ', 'waruwu@kku.ac.th ', '_YT1Se0AAAAJ', '51864959500', NULL, 0, NULL, 4, NULL, NULL, '2025-10-04 00:00:00', '2026-08-07 10:44:19', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Warunya Wunnasri', 'Ph.D.', '085-0022231', '08 5002 2231', '+668 5002 2231', '', 'Applied Intelligence and Data Analytics (AIDA) Lab', '', 'https://computing.kku.ac.th/warunya.wunnasri', 'A', '2026-08-07 10:44:19', NULL),
(1024, 'ศักดิ์พจน์', 'ทองเลี่ยมนาค', 'male', 'sakpod@kku.ac.th ', 'sakpod@kku.ac.th ', NULL, '57193264067', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Sakpod Tongleamnak', 'Ph.D.', '083-4662082', '08 3466 2082', '+668 3466 2082', '', '', '', 'https://computing.kku.ac.th/sakpod.tongleamnak', 'A', NULL, NULL),
(1025, 'เพชร', 'อิ่มทองคำ', 'male', 'phetim@kku.ac.th', 'phetim@kku.ac.th', 'HZNNCj4AAAAJ', '56208608600', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-07-11 10:12:07', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Phet Aimtongkham', 'Ph.D.', '084-3927080', '08 4392 7080', '+668 4392 7080', '', '', '', 'https://computing.kku.ac.th/phet.aimtongkham', 'A', '2026-07-11 10:12:07', NULL),
(1026, 'ไพรสันต์', 'ผดุงเวียง', 'male', 'praipa@kku.ac.th', 'praipa@kku.ac.th', 'bzF_BIkAAAAJ', '35179942700', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'ผศ. ดร.', '', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Praisan Padungweang', 'Ph.D.', '094-2653336', '09 4265 3336', '+669 4265 3336', '', 'Advanced Smart Computing (ASC) Lab', '', 'https://computing.kku.ac.th/praisan.padungweang', 'A', NULL, NULL),
(1027, 'ชานนท์', 'เดชสุภา', 'male', 'chanode@kku.ac.th', 'chanode@kku.ac.th', '_lza5VIAAAAJ', '54683571200', NULL, 0, '$2a$10$MIO3vHwBxuuF7Mo/Hd0QPuX3xDhYmsgm0jl/UHQt60OzO8M.zeQjW', 1, 1, '2025-10-01', '2025-10-04 00:00:00', '2026-08-10 13:42:36', NULL, 'รศ. ดร.', 'รองคณบดีฝ่ายวิจัยและนวัตกรรม', 'รองศาสตราจารย์', 'Associate Professor', 'Assoc. Prof.', 'Chanon Dechsupa', 'Ph.D.', '089-2175154', '08 9217 5154', '+668 9217 5154', '', '', '', 'https://computing.kku.ac.th/chanon.dechsupa', 'A', '2026-08-10 13:42:36', NULL),
(1028, 'ศาสตรา', 'วงศ์ธนวสุ', 'male', 'wongsar@kku.ac.th', 'wongsar@kku.ac.th', 'brgiVtgAAAAJ', '14051173200', NULL, 0, '$2a$10$nNzlMqNr1.as/H6nsOrPqu2FeXrnm.BKtoUWT.kipiqoySTWCZxmu', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-04-16 16:12:11', NULL, 'ศ. ดร.', '', 'ศาสตราจารย์', 'Professor', 'Prof.', 'Sartra Wongthanavasu', 'Ph.D.', '081-9650277', '08 1965 0277', '+668 1965 0277', '', 'Machine Learning and Intelligent Systems (MLIS) Lab', '', 'https://computing.kku.ac.th/sartra.wongthanavasu', 'A', '2026-04-16 16:12:11', NULL),
(1029, 'วาสนา', 'พุฒกลาง', 'female', 'putklang_w@kku.ac.th', 'putklang_w@kku.ac.th', 'vnTKGAcAAAAJ', '55349714900', NULL, 0, '$2a$10$Fg62Csnu9BXoshQhNzYny.7FlIXc/buPlSQv2mzu2yzCItXtB.29m', 1, NULL, NULL, '2025-10-04 00:00:00', '2025-12-23 10:27:16', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Wasana Putklang', 'Ph.D.', '086-7162373', '08-6716-2373', '+668 6716-2373', '', 'Geo-Informatics, NEGISTDA', 'SC9337', 'https://computing.kku.ac.th/wasana.putklang', 'A', NULL, NULL),
(1030, 'ภัคราช', 'มุสิกะวัน', 'male', 'pakamu@kku.ac.th', 'pakamu@kku.ac.th', 'dxQuB2QAAAAJ', '57192588751', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Pakarat Musikawan', 'Ph.D.', '083-4660399', '08 3466 0399 ', '+668 3466 0399 ', '', '', 'SC9349', 'https://computing.kku.ac.th/pakarat.musikawan', 'A', NULL, NULL),
(1031, 'ญานิกา', 'คงโสรส', 'female', 'yaniko@kku.ac.th', 'yaniko@kku.ac.th', 'zdBo3cwAAAAJ', '56205414600', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Yanika Kongsorot', 'Ph.D.', '084-6042660', '08 4604 2660', '+668 4604 2660', '', '', 'SC9348', 'https://computing.kku.ac.th/yanika.kongsorot', 'A', NULL, NULL),
(1032, 'Arfat', 'Khan', 'male', 'arfatkhan@kku.ac.th', 'arfatkhan@kku.ac.th', NULL, '58106961000', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Arfat Ahmad Khan', 'Ph.D.', '095-320-3915', '09 5320 3915\n', '', '', '', '', '', 'A', NULL, NULL),
(1033, 'พงษ์ศธร', 'จันทร์ยอย', 'male', 'pongsathon@kku.ac.th', 'pongsathon@kku.ac.th', 'fn94QPIAAAAJ', '56387548900', NULL, 0, '$2a$10$3s9NMfGV6vL0mcP8yTYTWuniQ6y5Bp11.g.JG74YK0ZBgq4gW/rti', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-07-13 10:38:10', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Pongsathon Janyoi', 'Ph.D.', '094-693-7606', '09 4693 7606', '+669 4693 7606', '', '', 'SC9348', '', 'A', '2026-07-13 10:38:10', NULL),
(1034, 'ไอศูรย์', 'กาญจนสุรัตน์', 'male', 'isoonkan@kku.ac.th', 'isoonkan@kku.ac.th', 'Vos5zq4AAAAJ', '57193649151', NULL, 0, '$2a$10$3TLdZo2RetUaF1TfCNzbVebg9Me0z9lNe5dWEIavgQ5ErAM4Bzt4y', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-06-22 09:08:57', NULL, 'ผศ. ดร.', 'ผู้ช่วยคณบดีฝ่ายแผนและประกันคุณภาพ', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Isoon Kanjanasurat', 'Ph.D.', '093-2624161', '09 3262 4161', '+669 3262 4161', '', '', 'SC9323', '', 'A', '2026-06-22 09:08:57', NULL),
(1035, 'จักรกฤษณ์', 'แก้วโยธา', 'male', 'jakkritk@kku.ac.th', 'jakkritk@kku.ac.th', 'hk7hj_gAAAAJ', '56688577200', NULL, 0, '$2a$10$vaBsfevyioeRVNbHMqKhOeDc4kxx7veQHd6Dgwr7Zkj.wDbENzj9m', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-08-07 21:20:32', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Jakkrit Kaewyotha', 'Ph.D.', '089-7140466', '08 9714 0466', '+668 9714 0466', '', '', 'SC9361', '', 'A', '2026-08-07 21:20:32', NULL),
(1036, 'สาธิต', 'กระเวนกิจ', 'male', 'satikr@kku.ac.th', 'satikr@kku.ac.th', 'wBQeptEAAAAJ', '55850885500', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2026-04-22 13:24:46', NULL, 'ผศ. ดร.', 'ผู้ช่วยคณบดีฝ่ายดิจิทัล', 'ผู้ช่วยศาสตราจารย์', 'Assistant Professor', 'Asst. Prof.', 'Satit Kravenkit', 'Ph.D.', '089-4177484', '08 9417 7484', '+668 9417 7484', '', '', '', '', 'A', '2026-04-22 13:24:46', NULL),
(1037, 'พบพร', 'ด่านวิรุทัย', 'male', 'pobda@kku.ac.th', 'pobda@kku.ac.th', 'EdGy9eEAAAAJ', '57188704115', NULL, 0, '$2a$10$l3iuJCJAwZOwdQzqeDF7WuGO1A0IoRz..CGct/eikx3dFEL8N2s2y', 1, NULL, NULL, '2025-10-04 00:00:00', '2026-04-06 10:57:59', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Pobporn Danvirutai', 'Ph.D.', '092-8719244', '', '', '', '', '', '', 'A', '2026-04-06 10:57:59', NULL),
(1038, 'วันเฉลิม', 'นัดดา', 'male', 'wannad@kku.ac.th', 'wannad@kku.ac.th', 'ZmxX5qoAAAAJ', '57214759535', NULL, 0, NULL, 1, NULL, NULL, '2025-10-04 00:00:00', '2025-10-04 00:00:00', NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', '', 'Wanchaloem Nadda', '', '062-8428362', '', '', '', '', '', '', 'A', NULL, NULL),
(1039, 'จุฑารัตน์', 'อุ่มไธสง', 'female', 'jutaum@kku.ac.th', 'jutaum@kku.ac.th', NULL, NULL, NULL, 0, '$2a$10$h.ILsvKAdo0LAU15A7hgk.OYtrC9x1ltHgZGsVedwNa1MGTkPlOqW', 3, NULL, NULL, '2025-10-05 23:44:04', '2026-08-10 15:29:43', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', '2026-08-10 15:29:43', NULL),
(1040, 'ขวัญจิรา', 'จรรยากรณ์', 'female', 'khwunch@kku.ac.th', 'khwunch@kku.ac.th', NULL, NULL, NULL, 0, '$2a$10$7/zaqf.f8vOeOE9sbBGyVO81MEJ3HiziUjGqIFGjf30V7eZ21zNpK', 3, NULL, NULL, '2025-12-18 00:00:00', '2025-12-18 15:16:14', NULL, 'น.ส.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1041, 'จิราภรณ์', 'หอมอ่อน', 'female', 'jiraho@kku.ac.th', 'jiraho@kku.ac.th', NULL, NULL, NULL, 0, '$2a$10$u.EQGYqKfs3iLpYKuMOUpOYh.k.j4HU/W9Jv/jfZ30hJoWwnBASH6', 2, NULL, NULL, '2025-12-23 00:00:00', '2025-12-23 15:19:44', NULL, 'น.ส.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1043, 'ชาติชาย', 'ปุณริบูรณ์', 'male', 'chatpu@kku.ac.th', 'chatpu@kku.ac.th', NULL, '55129231700', NULL, 0, NULL, 1, NULL, NULL, '2026-04-04 00:31:42', NULL, NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1044, 'ณัฐพล', 'เจริญชัย', 'male', 'nattjar@kku.ac.th', 'nattjar@kku.ac.th', NULL, '57222272749', NULL, 0, NULL, 1, NULL, NULL, '2026-04-04 00:31:42', NULL, NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1045, 'ธีรพงศ์', 'ปานบุญยืน', 'male', 'teerpa@kku.ac.th', 'teerpa@kku.ac.th', NULL, '57194783124', NULL, 0, NULL, 1, NULL, NULL, '2026-04-04 00:31:42', NULL, NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1046, 'เจษฎา', 'ทองก้านเหลือง', 'male', 'jedtho@kku.ac.th', 'jedtho@kku.ac.th ', NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, '2026-04-04 00:31:42', NULL, NULL, 'อ. ดร.', '', 'อาจารย์', 'Lecturer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL),
(1047, 'นิภาดา', 'ญายะนันท์', NULL, 'niphada.y@kkumail.com', NULL, NULL, NULL, NULL, 0, NULL, 1, NULL, NULL, '2026-07-12 16:03:20', '2026-07-24 20:22:15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', '2026-07-24 20:22:15', NULL),
(1048, 'ณัฐรภา', 'ศรีวิชา', NULL, 'natrapa.s@kkumail.com', NULL, NULL, NULL, NULL, 0, '$2a$10$TeSru2c2Nv9X9jmuchGzX.4FARjjQ9PojLapTZkFC63hgAbr.zai.', 6, NULL, NULL, '2026-07-12 16:03:20', '2026-08-04 13:57:32', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', '2026-08-04 13:57:32', NULL),
(1049, 'การติมา', 'คำภีร์', NULL, 'karntima.k@kkumail.com', NULL, NULL, NULL, NULL, 0, NULL, 3, NULL, NULL, '2026-07-12 16:03:20', '2026-07-13 20:59:37', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', '2026-07-13 20:59:37', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD KEY `role_id` (`role_id`),
  ADD KEY `position_id` (`position_id`),
  ADD KEY `idx_email` (`email`),
  ADD KEY `idx_fullname` (`user_fname`,`user_lname`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1050;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `users`
--
ALTER TABLE `users`
  ADD CONSTRAINT `users_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`role_id`),
  ADD CONSTRAINT `users_ibfk_2` FOREIGN KEY (`position_id`) REFERENCES `positions` (`position_id`);

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
