-- =============================================================================
-- V1__baseline.sql — Flyway Baseline Migration
--
-- This migration represents the existing schema that was previously managed
-- by Hibernate ddl-auto=update. All tables already exist in the database.
--
-- Going forward:
--   • ddl-auto is set to 'validate' (Hibernate checks but never modifies)
--   • All schema changes MUST be added as new migration files (V2__, V3__, ...)
--   • Flyway's baseline-on-migrate=true + baseline-version=0 means this file
--     is skipped; the first real migration will be V2__
--
-- Created: 2026-08-22 as part of ISO/IEC 27001 compliance (A.14)
-- =============================================================================

-- Intentionally empty: the schema already exists.
-- This file exists solely to establish Flyway's migration history table.
