package com.ecom;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Actually runs every migration, rather than only scanning them.
 *
 * <p>Nothing else in the build executes this SQL: the test profile sets
 * {@code spring.flyway.enabled=false} and builds its schema from the entities
 * instead. That left the migrations completely unexercised — which is how two of
 * them sat in the repository written in MySQL syntax against a PostgreSQL
 * database, unable to run at all.
 *
 * <p><b>Scope: V0–V4 only.</b> V5 and V6 use PostgreSQL partial indexes
 * ({@code CREATE UNIQUE INDEX ... WHERE ...}), which H2 does not support in any
 * form — neither partial nor expression indexes. Rewriting them to suit H2 would
 * weaken the constraints on the real database, so they are left correct and left
 * untested here; they still need one run against real PostgreSQL before deploy.
 *
 * <p>What this does cover is the whole class of failure that was actually
 * present: SQL that cannot execute on PostgreSQL at all, and migrations ordered
 * so their foreign keys cannot resolve. Both were true of V1 and V2.
 */
@DisplayName("รัน Flyway migration จริงทั้งชุด")
class FlywayMigrationRunTest {

    /**
     * Stand-ins for the tables the migrations reference but do not create.
     *
     * <p>The real schema predates Flyway here — V0 is an empty baseline marking
     * everything that already existed. Only the columns the migrations point at
     * are needed.
     */
    private static final String[] PRE_EXISTING_TABLES = {
            "CREATE TABLE IF NOT EXISTS user_dtls (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " email VARCHAR(255))",
            "CREATE TABLE IF NOT EXISTS academic_request (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
            "CREATE TABLE IF NOT EXISTS position_request (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
            "CREATE TABLE IF NOT EXISTS staff_member (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " first_name VARCHAR(255), last_name VARCHAR(255))",
    };

    private String freshDatabaseUrl() {
        return "jdbc:h2:mem:flywayrun" + System.nanoTime()
                + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";
    }

    @Test
    @DisplayName("ทุก migration รันผ่านตามลำดับ และสร้างตารางครบ")
    void allMigrationsApply() throws Exception {
        String url = freshDatabaseUrl();

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            for (String ddl : PRE_EXISTING_TABLES) {
                st.execute(ddl);
            }
        }

        MigrateResult result = Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .target(org.flywaydb.core.api.MigrationVersion.fromVersion("4"))
                .load()
                .migrate();

        System.out.println("PROBE_APPLIED: " + result.migrationsExecuted);
        result.migrations.forEach(m ->
                System.out.println("PROBE_RAN: v" + m.version + " " + m.description));

        assertThat(result.success).isTrue();

        // Every table the migrations are responsible for must now exist.
        List<String> tables = new ArrayList<>();
        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement();
                ResultSet rs = st.executeQuery(
                        // Case-insensitive: DATABASE_TO_LOWER makes these lowercase.
                        "SELECT table_name FROM information_schema.tables "
                                + "WHERE UPPER(table_schema) = 'PUBLIC'")) {
            while (rs.next()) {
                tables.add(rs.getString(1).toLowerCase());
            }
        }
        System.out.println("PROBE_TABLES: " + tables);

        assertThat(tables).contains(
                "petitions",              // V1 — เคยพังเพราะ syntax MySQL
                "petition_statuses",      // V1 — เคยพังเพราะ FK ชี้ไปตารางที่ V2 เพิ่งสร้าง
                "academic_document_edit_log"); // V3
    }

    @Test
    @DisplayName("V4 เพิ่มคอลัมน์ user_id ให้ staff_member ได้จริง")
    void v4AddsTheStaffAccountLink() throws Exception {
        String url = freshDatabaseUrl();

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            for (String ddl : PRE_EXISTING_TABLES) {
                st.execute(ddl);
            }
        }

        Flyway.configure().dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true).baselineVersion("0")
                .target(org.flywaydb.core.api.MigrationVersion.fromVersion("4"))
                .load().migrate();

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement();
                ResultSet rs = st.executeQuery(
                        "SELECT data_type FROM information_schema.columns "
                                + "WHERE UPPER(table_name) = 'STAFF_MEMBER' "
                                + "AND UPPER(column_name) = 'USER_ID'")) {
            assertThat(rs.next()).as("staff_member.user_id ต้องถูกสร้างโดย V4").isTrue();
            System.out.println("PROBE_STAFF_USER_ID_TYPE: " + rs.getString(1));
        }
    }

    @Test
    @DisplayName("รันซ้ำบนฐานที่ migrate แล้ว ต้องไม่พังและไม่ทำอะไรเพิ่ม")
    void reRunningIsIdempotent() throws Exception {
        String url = freshDatabaseUrl();

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            for (String ddl : PRE_EXISTING_TABLES) {
                st.execute(ddl);
            }
        }

        var flyway = Flyway.configure().dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true).baselineVersion("0")
                .target(org.flywaydb.core.api.MigrationVersion.fromVersion("4"))
                .load();

        flyway.migrate();
        MigrateResult second = flyway.migrate();

        // A restart must not try to apply anything again.
        assertThat(second.success).isTrue();
        assertThat(second.migrationsExecuted).isZero();
    }
}
