package com.ecom;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Runs V11 for real and proves it clears a stale enum check.
 *
 * <p>Hibernate emits {@code check (col in (...))} for every
 * {@code @Enumerated(EnumType.STRING)} column, freezing the enum's values as they
 * stood when the table was created, and {@code ddl-auto=update} never rewrites it
 * afterwards. {@code signature_audit_event_event_type_check} froze at ten values,
 * so adding {@code FORWARDED} broke ส่งเวียนลงนามต่อ outright: the audit insert
 * was rejected, PostgreSQL aborted the transaction, and the whole forwarding
 * operation went down with it. Dropping the constraint leaves enum membership to
 * the Java enum — the only place it stays in step with the code.
 *
 * <p>This ran nowhere before. Flyway had never executed against this project at
 * all: Boot 4 moved its auto-configuration into the separate
 * {@code spring-boot-flyway} module, and without that dependency
 * {@code flyway-core} sat on the classpath doing nothing while every
 * {@code spring.flyway.*} property was ignored.
 *
 * <p>Only V11 is exercised here. V5 and V6 use PostgreSQL partial indexes that H2
 * cannot execute — see {@link FlywayMigrationRunTest} — so the tables V11 targets
 * are stood up directly instead.
 */
@DisplayName("V11 ลบ CHECK constraint เก่าของคอลัมน์ enum")
class V11DropsStaleEnumCheckTest {

    /** The tables V11 names, as Hibernate would have left them. */
    private static final String[] SCHEMA_AS_HIBERNATE_BUILT_IT = {
            // The stale constraint at the heart of the bug: no FORWARDED.
            "CREATE TABLE IF NOT EXISTS signature_audit_event ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " event_type VARCHAR(30) NOT NULL,"
                    + " CONSTRAINT signature_audit_event_event_type_check"
                    + " CHECK (event_type IN ('CREATED','NOTIFIED','REMINDED','VIEWED','SIGNED',"
                    + "'DECLINED','CANCELLED','COMPLETED','VOIDED','EXPIRED')))",
            "CREATE TABLE IF NOT EXISTS signature_request (id BIGINT PRIMARY KEY, status VARCHAR(30), module VARCHAR(20))",
            "CREATE TABLE IF NOT EXISTS signature_step (id BIGINT PRIMARY KEY, status VARCHAR(20))",
            "CREATE TABLE IF NOT EXISTS user_signature (id BIGINT PRIMARY KEY, kind VARCHAR(20))",
            "CREATE TABLE IF NOT EXISTS document_workflow_config (id BIGINT PRIMARY KEY, module VARCHAR(20))",
    };

    private String databaseWithStaleConstraint() throws Exception {
        String url = "jdbc:h2:mem:v11probe" + System.nanoTime()
                + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";
        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            for (String ddl : SCHEMA_AS_HIBERNATE_BUILT_IT) {
                st.execute(ddl);
            }
        }
        return url;
    }

    /** Applies V11 alone, baselining past the migrations H2 cannot run. */
    private MigrateResult applyV11(String url) {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("10")
                .target(MigrationVersion.fromVersion("11"))
                .load()
                .migrate();
    }

    @Test
    @DisplayName("ก่อนรัน V11: บันทึก FORWARDED ไม่ได้ (ยืนยันว่าบั๊กมีจริง)")
    void forwardedIsRejectedBeforeTheMigration() throws Exception {
        String url = databaseWithStaleConstraint();

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            assertThat(insertForwarded(st))
                    .as("ถ้าแถวนี้บันทึกผ่านตั้งแต่ต้น แปลว่าไม่ได้จำลองบั๊กจริง")
                    .isFalse();
        }
    }

    @Test
    @DisplayName("หลังรัน V11: บันทึก FORWARDED ได้ และ constraint หายไป")
    void v11DropsTheConstraintSoForwardedCanBeRecorded() throws Exception {
        String url = databaseWithStaleConstraint();

        MigrateResult result = applyV11(url);

        assertThat(result.success).isTrue();
        assertThat(result.migrationsExecuted).as("V11 ต้องถูกรันจริง").isEqualTo(1);

        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            assertThat(insertForwarded(st))
                    .as("หลัง V11 แล้ว ส่งเวียนลงนามต่อต้องบันทึก audit event ได้")
                    .isTrue();
        }
    }

    @Test
    @DisplayName("รัน V11 บนฐานที่ไม่มี constraint อยู่แล้ว ต้องไม่พัง")
    void v11IsSafeWhereTheConstraintWasNeverThere() throws Exception {
        String url = "jdbc:h2:mem:v11fresh" + System.nanoTime()
                + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE";
        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement st = c.createStatement()) {
            // Same tables, but never carrying the check — a database built after the fix.
            st.execute("CREATE TABLE signature_audit_event ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type VARCHAR(30) NOT NULL)");
            for (int i = 1; i < SCHEMA_AS_HIBERNATE_BUILT_IT.length; i++) {
                st.execute(SCHEMA_AS_HIBERNATE_BUILT_IT[i]);
            }
        }

        assertThatCode(() -> applyV11(url))
                .as("DROP CONSTRAINT IF EXISTS ต้องผ่านแม้ไม่มี constraint ให้ลบ")
                .doesNotThrowAnyException();
    }

    /** @return true if the row was accepted. */
    private boolean insertForwarded(Statement st) {
        try {
            st.execute("INSERT INTO signature_audit_event (event_type) VALUES ('FORWARDED')");
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}
